sudo: required

language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pip

services:
  - docker

cache:
  - pip

before_install:
  # Docker-CE Installation
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Requirements for container environment
  # - pip install virtualenv
  # - virtualenv --python=/usr/bin/python2.7 .venv_container_env/
  # - .venv_container_env/bin/pip install -r tests/requirements.txt
  # - .venv_container_env/bin/ansible-galaxy install -r tests/container-environment/requirements.yml
  - pip install -r tests/requirements.txt

install:
  # Requirements for tests messaging_abstraction and messaging_components
  - pip install -r messaging_abstraction/tests/requirements.txt -r messaging_components/tests/requirements.txt

  # Test suite requirements
  - pip install -r requirements.txt

  # Setup test suite containers environment
  - source .venv_container_env/bin/activate && cd tests && make all && deactivate
  - export ROUTER1=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' router1)
  - export BROKER1=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' broker1)
  - docker ps -a

jobs:
  include:
    - stage: Messaging Abstraction module tests
      script:
        - py.test messaging_abstraction/tests

    - stage: Messaging Components module tests
      script:
        - py.test messaging_components/tests

#    - stage: Router simple testsuite
#      script:
#        # Test suite
#        - py.test test-suite/router \
#            --sender native \
#            --receiver native \
#            --inventory  \
#            -s --verbose
