sudo: required

language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pip

services:
  - docker

cache:
  - pip

before_install:
  # Docker-CE Installation
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  # Activate virtualenv for topology setup
  - pip install virtualenv
  - virtualenv .venv_container_env/
  - source .venv_container_env/bin/activate

  # Requirements for tests messaging_abstraction and messaging_components
  - |
    pip install -r messaging_abstraction/requirements.txt \
                -r messaging_components/requirements.txt \
                -r messaging_abstraction/tests/requirements.txt \
                -r messaging_components/tests/requirements.txt \
                -r tests/requirements.txt

  # Debug purpose
  - ansible --version
  - docker --version
  - python -c 'import docker; d = docker.from_env(); print(d);'

  # Setup test suite containers environment
  - cd tests && make all
  - export ROUTER1=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' router1)
  - export BROKER1=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' broker1)

  # Debug containers
  - docker ps -a


jobs:
  include:
    - stage: Messaging Abstraction module tests
      script:
        - py.test messaging_abstraction/tests

    - stage: Messaging Components module tests
      script:
        - py.test messaging_components/tests
