sudo: required

language: python

python:
  - "3.6"

addons:
  apt:
    packages:
      - python-pip

cache:
  - pip

before_install:
  # Docker-CE Installation
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Requirements for container environment
  - pip install virtualenv
  - virtualenv --python=/usr/bin/python2.7 .venv_container_env/
  - .venv_container_env/bin/pip install https://github.com/ansible/ansible/archive/devel.tar.gz docker-py docker-compose
  - .venv_container_env/bin/ansible-galaxy install -r tests/container-environment/requirements.yml

install:
  # Requirements for tests messaging_abstraction and messaging_components
  - pip install -r messaging_abstraction/tests/requirements.txt -r messaging_components/tests/requirements.txt

  # Test suite requirements
  - pip install -r requirements.txt

  # Setup test suite containers environment
  - source .venv_container_env/bin/activate && cd tests && make all && deactivate
  - docker ps -a

script:
#  - py.test tests/selftests \
#    --sender native --sender nodejs --sender python \
#    --receiver native --receiver nodejs --receiver python \
#    --router dispatch --router interconnect \
#    --broker artemis --broker amq7  --broker amq6 \
#    --tls tls10 --tls tls11 --tls tls12 --tls tls13 \
#    --inventory /home/enkeys/ansible/hosts \
#    -s --verbose s

  # Messaging Abstraction module tests
  - py.test messaging_abstraction/tests
  # Messaging Components module tests
  - py.test messaging_components/tests

  # Test suite